import{a as q,S as w,i as s}from"./assets/vendor-DXaqCXe3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const E="49357891-7b2a70058984a44bc943728d9",S="https://pixabay.com/api/";async function d(e,r=1,i=15){try{const a=await q.get(S,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i}});return{images:a.data.hits,totalHits:a.data.totalHits}}catch(a){throw console.error("Error fetching images:",a),new Error("Failed to fetch images.")}}const m=document.querySelector(".gallery");let P=new w(".gallery a");function y(e){const r=e.map(({webformatURL:i,largeImageURL:a,tags:t,likes:o,views:l,comments:L,downloads:b})=>`
        <li class="gallery-item">
            <a href="${a}" class="gallery-link">
                <img src="${i}" alt="${t}" loading="lazy">
            </a>
            <ul class="info">
                <li> 👍 ${o}</li>
                <li> 👀 ${l}</li>
                <li> 💬 ${L}</li>
                <li> 📥 ${b}</li>
            </ul>
        </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),P.refresh()}function v(){m.innerHTML=""}s.settings({position:"topRight",iconColor:"#fff",messageColor:"#fff"});const H=document.querySelector(".form");document.querySelector(".gallery");const $=document.querySelector(".loader"),h=document.querySelector(".load-more");let c="",n=1;const u=15;H.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target.elements["search-text"].value.trim(),!c){s.warning({title:"Warning",message:"Please enter a search query!"});return}n=1,v(),g(!1),f(!0);try{const{images:r,totalHits:i}=await d(c,n,u);O(r,i)}catch{s.error({title:"Error",message:"Failed to fetch images."})}finally{f(!1)}});h.addEventListener("click",async()=>{n+=1,f(!0),g(!1);try{const{images:e,totalHits:r}=await d(c,n,u);y(e),p(r),x()}catch{s.error({title:"Error",message:"Failed to fetch images."})}finally{f(!1)}});function O(e,r){e.length===0?s.error({title:"Error",message:"No images found. Try another query."}):(y(e),p(r))}function p(e){n*u>=e?s.info({message:"We're sorry, but you've reached the end of search results."}):g(!0)}function f(e){$.classList.toggle("hidden",!e)}function g(e){h.classList.toggle("hidden",!e)}function x(){const e=document.querySelector(".gallery-item");if(e){const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
